### ISSUE TITLE
This extension removes the original HTML language support. 

### ISSUE THREAD

**Issue by robjac** [Drunces/vscode-rails#1]
When this extension is installed, I've noticed that language support for regular/vanilla HTML files is lost. HTML is not an option when "configuring the language for this file extension" or "configure File Association for '.html'. The only available option is html.erb, which is fine when i'm working on a .erb file -- but i still need formatting to happen for plain HTML (vscode default file association). As such, I've had to uninstall your extension 😢 , and I really don't want to.

**Comment by robjac** [comment]
Let me know if you need anymore details.

**Comment by VenseChang** [comment]
@robjac sorry for the inconvenience. I will fix it quickly.

**Comment by VenseChang** [comment]
@robjac  
It fixed in latest release v0.5.0，you can update and try again. Thanks for bug report 👍

**Comment by robjac** [comment]
No problem! thanks!
